on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  server-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and export
        uses: docker/build-push-action@v5
        with:
          context: ./test-server
          tags: rc-server:latest
          outputs: type=docker,dest=/tmp/rc-server.tar

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: rc-server
          path: /tmp/rc-server.tar

  server-use:
    runs-on: ubuntu-latest
    needs: server-build
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: rc-server
          path: /tmp

      - name: Load image
        run: |
          docker load --input /tmp/rc-server.tar
          docker image ls -a

      - name: Run the image
        run: |
          docker run -d -p 4500:4500 --name rc-server rc-server:latest
          docker ps -a

      - name: Check port mapping
        run: |
          docker port rc-server
          sleep 5
          docker logs rc-server
          curl http://localhost:4500